# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/minimop/Workspace/DreamOfBlocks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/minimop/Workspace/DreamOfBlocks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/minimop/Workspace/DreamOfBlocks/CMakeFiles /Users/minimop/Workspace/DreamOfBlocks//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/minimop/Workspace/DreamOfBlocks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

src/event_handler.o: src/event_handler.c.o
.PHONY : src/event_handler.o

# target to build an object file
src/event_handler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/event_handler.c.o
.PHONY : src/event_handler.c.o

src/event_handler.i: src/event_handler.c.i
.PHONY : src/event_handler.i

# target to preprocess a source file
src/event_handler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/event_handler.c.i
.PHONY : src/event_handler.c.i

src/event_handler.s: src/event_handler.c.s
.PHONY : src/event_handler.s

# target to generate assembly for a file
src/event_handler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/event_handler.c.s
.PHONY : src/event_handler.c.s

src/input_handler.o: src/input_handler.c.o
.PHONY : src/input_handler.o

# target to build an object file
src/input_handler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/input_handler.c.o
.PHONY : src/input_handler.c.o

src/input_handler.i: src/input_handler.c.i
.PHONY : src/input_handler.i

# target to preprocess a source file
src/input_handler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/input_handler.c.i
.PHONY : src/input_handler.c.i

src/input_handler.s: src/input_handler.c.s
.PHONY : src/input_handler.s

# target to generate assembly for a file
src/input_handler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/input_handler.c.s
.PHONY : src/input_handler.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.c.s
.PHONY : src/main.c.s

src/player.o: src/player.c.o
.PHONY : src/player.o

# target to build an object file
src/player.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/player.c.o
.PHONY : src/player.c.o

src/player.i: src/player.c.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/player.c.i
.PHONY : src/player.c.i

src/player.s: src/player.c.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/player.c.s
.PHONY : src/player.c.s

src/resource_tracker.o: src/resource_tracker.c.o
.PHONY : src/resource_tracker.o

# target to build an object file
src/resource_tracker.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/resource_tracker.c.o
.PHONY : src/resource_tracker.c.o

src/resource_tracker.i: src/resource_tracker.c.i
.PHONY : src/resource_tracker.i

# target to preprocess a source file
src/resource_tracker.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/resource_tracker.c.i
.PHONY : src/resource_tracker.c.i

src/resource_tracker.s: src/resource_tracker.c.s
.PHONY : src/resource_tracker.s

# target to generate assembly for a file
src/resource_tracker.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/resource_tracker.c.s
.PHONY : src/resource_tracker.c.s

src/scene_3d_game.o: src/scene_3d_game.c.o
.PHONY : src/scene_3d_game.o

# target to build an object file
src/scene_3d_game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/scene_3d_game.c.o
.PHONY : src/scene_3d_game.c.o

src/scene_3d_game.i: src/scene_3d_game.c.i
.PHONY : src/scene_3d_game.i

# target to preprocess a source file
src/scene_3d_game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/scene_3d_game.c.i
.PHONY : src/scene_3d_game.c.i

src/scene_3d_game.s: src/scene_3d_game.c.s
.PHONY : src/scene_3d_game.s

# target to generate assembly for a file
src/scene_3d_game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/scene_3d_game.c.s
.PHONY : src/scene_3d_game.c.s

src/voxel.o: src/voxel.c.o
.PHONY : src/voxel.o

# target to build an object file
src/voxel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/voxel.c.o
.PHONY : src/voxel.c.o

src/voxel.i: src/voxel.c.i
.PHONY : src/voxel.i

# target to preprocess a source file
src/voxel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/voxel.c.i
.PHONY : src/voxel.c.i

src/voxel.s: src/voxel.c.s
.PHONY : src/voxel.s

# target to generate assembly for a file
src/voxel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/voxel.c.s
.PHONY : src/voxel.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... game"
	@echo "... src/event_handler.o"
	@echo "... src/event_handler.i"
	@echo "... src/event_handler.s"
	@echo "... src/input_handler.o"
	@echo "... src/input_handler.i"
	@echo "... src/input_handler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/resource_tracker.o"
	@echo "... src/resource_tracker.i"
	@echo "... src/resource_tracker.s"
	@echo "... src/scene_3d_game.o"
	@echo "... src/scene_3d_game.i"
	@echo "... src/scene_3d_game.s"
	@echo "... src/voxel.o"
	@echo "... src/voxel.i"
	@echo "... src/voxel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

