#ifndef SCENE_3D_GAME_H
#define SCENE_3D_GAME_H

#define MAX_SCREEN_WIDTH 1400
#define MAX_SCREEN_HEIGHT 900
#define CURSOR_RADIUS 2

#define TARGET_FPS 4000
#define BLOCK_SIZE 1.0f
#define HALF_BLOCK_SIZE (BLOCK_SIZE / 2.0f)
#define MAX_PLACMENT_DISTANCE 1000.0

int Scene3DGame(void);

#endif // SCENE_3D_GAME_H
