#ifndef SCENE_3D_GAME_H
#define SCENE_3D_GAME_H

#define MAX_SCREEN_WIDTH 1200
#define MAX_SCREEN_HEIGHT 800
#define CURSOR_RADIUS 2

#define PLAYGROUND_Y_MAX 8
#define PLAYGROUND_X_MAX 32
#define PLAYGROUND_Z_MAX 32

#define TARGET_FPS 820
#define BLOCK_SIZE 1.0f
#define HALF_BLOCK_SIZE (BLOCK_SIZE / 2.0f)
#define MAX_PLACMENT_DISTANCE 1000.0

int Scene3DGame(void);

#endif // SCENE_3D_GAME_H
